project_id = "agsarxzqbvkdcoqjtifk"

[functions.process-document]
verify_jwt = true

[functions.generate-study-materials]
verify_jwt = false

[auth]
enabled = true
external_email_enabled = true

[auth.email]
enable_signup = true
double_confirm_changes = false
enable_confirmations = false
template = { invite = "", confirmation = "", recovery = "", magic_link = "", email_change = "" }