// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://agsarxzqbvkdcoqjtifk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFnc2FyeHpxYnZrZGNvcWp0aWZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2NDA4MjIsImV4cCI6MjA3MTIxNjgyMn0.LIDd67V5UCJ_XyOi2-7xcVYV-BJmsoFdVqDe9i3ASAQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});